services:
  conect:
    container_name: conect
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./postgres_utils:/postgres_utils
    env_file:
      - .env      
    command: python conect.py
## ative a rede abaixo caso seja necessario
#     networks:
#       - web

# networks:
#   web:
#     external: true    